pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    //sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                    sh "docker build -f 02-primer-pipeline/Dockerfile -t feralexis007/homer_page:1.0.0-${BUILD_ID} 02-primer-pipeline"
                }
            }
        }
        stage('docker push') {
            steps{
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    script {
                        // Login to Docker Hub with username and token
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                        // Build the Docker image
                        sh "docker push feralexis007/homer_page:1.0.0-${BUILD_ID}"
                    }
                }
            }            
        }
    }
}